### ISSUE TITLE
NLog can't parse configuration when adding Logzio as target in XML config

### ISSUE THREAD

**Issue by Luminaii** [logzio/logzio-dotnet#13]
Hello,

NLog raises the following error when I try to add Logzio as target:
`rror Parsing configuration from *\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing *\NLog.config.  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.get_DeclaringType()
   at TinyIoC.TinyIoCContainer.<AutoRegisterInternal>b__112_2(Type type) in C:\dev\logzio-dotnet\src\Core\Bootstrap\TinyIoc.cs:line 3428
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TinyIoC.TinyIoCContainer.AutoRegisterInternal(IEnumerable`1 assemblies, DuplicateImplementationActions duplicateAction, Func`2 registrationPredicate) in C:\dev\logzio-dotnet\src\Core\Bootstrap\TinyIoc.cs:line 3427
   at TinyIoC.TinyIoCContainer.AutoRegister() in C:\dev\logzio-dotnet\src\Core\Bootstrap\TinyIoc.cs:line 1354
   at Logzio.DotNet.NLog.LogzioTarget..ctor() in C:\dev\logzio-dotnet\src\NLogShipper\LogzioTarget.cs:line 37
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NLog.Internal.FactoryHelper.CreateInstance(Type t)
   at NLog.Config.Factory`2.TryCreateInstance(String itemName, TBaseType& result)
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2018-07-16 19:19:22.3651 Warn NLog configuration while reloading Exception: NLog.NLogConfigurationException: Configuration.Reload() failed. Invalid XML?
   at NLog.LogFactory.ReloadConfigOnTimer(Object state)`

When I remove the target it works just fine.

**Comment by snakefoot** [comment]
Think that TinyIoC should be removed from this library, as the code looks like a can of worms.

And when looking at TinyIoC github-page, then lots of open issues and unfinished PRs trying to block the leaks.

Not sure why this library uses the TinyIoC-logic, besides making its unit-test a little prettier (Calling the default contructor instead of the explicit contructor with interface-parameters)

**Comment by snakefoot** [comment]
Have added fallback to default configuration, when TinyIOC fails to operate. See PR #16

**Comment by yellowblood** [comment]
Hey, I agree that TinyIOC was an overkill. Can be easily removed or replaced with a better DI solution.
