### ISSUE TITLE
Using logzio appender for log4net with application running .Net 4.0

### ISSUE THREAD

**Issue by yanivmad** [logzio/logzio-dotnet#3]
Hi,
Our app is running on .Net 4.0 and we managed to use the logzio appender correctly (most of the time).
But we got this error while running on WinXP:
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task System.Threading.Tasks.Task.Run(System.Action)'.
   at Logzio.DotNet.Core.Shipping.Shipper.SendLogs(ShipperOptions options, Boolean flush)
   at Logzio.DotNet.Core.Shipping.Shipper.Flush(ShipperOptions options)
   at Logzio.DotNet.Log4net.LogzioAppender.OnClose()
   at log4net.Appender.AppenderSkeleton.Close()
   at log4net.Util.AppenderAttachedImpl.RemoveAllAppenders()

Apparently we need this appender in .Net 4.0

**Comment by yellowblood** [comment]
Hey, you might be able to make it work by changing the `Task.Run` code to:

    var task = Task.Factory.StartNew(() => DoAction());

This is the old .NET 4 syntax.
